---
arguments:
  team: DCOPS
  os: Windows2016Standard 10.0  # || Ubuntu 16 || Windows 2012 || Ubuntu 14 || Windows2012 6.2
  role: roles::default
  prod-sc:
    hostname_template: handrade-2k16-%01d
    machine_size: t2.small
    network: default
  disks:
    - size_gb: 60